import java.util.Random;

public class MurderButton implements PushButton{
    int race;
    Random rnd = new Random();
    String[][] first = new String[7][20];
    String[][] last = new String[7][10];
    String[] death = new String[20];
    String status = new String();
    public MurderButton() {
        first[0][1] = "Jake";
        first[0][2] = "Connor";
        first[0][3] = "Eric";
        first[0][4] = "Kyle";
        first[0][5] = "Josh";
        first[0][6] = "Cody";
        first[0][7] = "Matt";
        first[0][8] = "Scott";
        first[0][9] = "Dylan";
        first[0][10] = "Max";
        first[0][11] = "Amy";
        first[0][12] = "Claire";
        first[0][13] = "Emily";
        first[0][14] = "Katie";
        first[0][15] = "Maddie";
        first[0][16] = "Jessica";
        first[0][17] = "Abby";
        first[0][18] = "Hannah";
        first[0][19] = "Betty";
        first[0][0] = "Molly";
        first[1][1] = "De'Quaie";
        first[1][2] = "Tyrone";
        first[1][3] = "Darnell";
        first[1][4] = "Malik";
        first[1][5] = "Trevon";
        first[1][6] = "Jamal";
        first[1][7] = "Dominique";
        first[1][8] = "Andre";
        first[1][9] = "Darryl";
        first[1][10] = "Terrance";
        first[1][11] = "Leshawna";
        first[1][12] = "Jamsmine";
        first[1][13] = "Raven";
        first[1][14] = "Ebony";
        first[1][15] = "Shanice";
        first[1][16] = "Aliyah";
        first[1][17] = "Diamond";
        first[1][18] = "Tiara";
        first[1][19] = "Kiara";
        first[1][0] = "Alexus";
        first[2][1] = "Jose";
        first[2][2] = "Alejandro";
        first[2][3] = "Luis";
        first[2][4] = "Carlos";
        first[2][5] = "Jorge";
        first[2][6] = "Pedro";
        first[2][7] = "Jesus";
        first[2][8] = "Manuel";
        first[2][9] = "Santiago";
        first[2][10] = "Juan";
        first[2][11] = "Sofia";
        first[2][12] = "Valentina";
        first[2][13] = "Isabella";
        first[2][14] = "Camila";
        first[2][15] = "Valeria";
        first[2][16] = "Mariana";
        first[2][17] = "Gabriela";
        first[2][18] = "Martina";
        first[2][19] = "Lucia";
        first[2][0] = "Fernanda";
        first[3][1] = "Aleksandr";
        first[3][2] = "Vladislav";
        first[3][3] = "Jakub";
        first[3][4] = "Jan";
        first[3][5] = "Luka";
        first[3][6] = "Lazar";
        first[3][7] = "Amar";
        first[3][8] = "Georgi";
        first[3][9] = "Miro";
        first[3][10] = "Ivan";
        first[3][11] = "Alena";
        first[3][12] = "Kamilia";
        first[3][13] = "Danica";
        first[3][14] = "Hana";
        first[3][15] = "Karol";
        first[3][16] = "Mara";
        first[3][17] = "Paulina";
        first[3][18] = "Sonia";
        first[3][19] = "Tania";
        first[3][0] = "Marlena";
        first[4][1] = "Haoda";
        first[4][2] = "Minjoon";
        first[4][3] = "Jihoon";
        first[4][4] = "Joonsuh";
        first[4][5] = "Hyeonwoo";
        first[4][6] = "Yejoon";
        first[4][7] = "Geonwoo";
        first[4][8] = "Minjae";
        first[4][9] = "Woojin";
        first[4][10] = "Gun";
        first[4][11] = "Seoyeon";
        first[4][12] = "Minsuh";
        first[4][13] = "Seohyeon";
        first[4][14] = "Jiwoo";
        first[4][15] = "Seoyoon";
        first[4][16] = "Jimin";
        first[4][17] = "Soobin";
        first[4][18] = "Haeun";
        first[4][19] = "Yeeun";
        first[4][0] = "Yoonsuh";
        first[5][1] = "Kareem";
        first[5][2] = "Tilak";
        first[5][3] = "Paresh";
        first[5][4] = "Mitra";
        first[5][5] = "Vyasa";
        first[5][6] = "Abhidi";
        first[5][7] = "Girik";
        first[5][8] = "Hari";
        first[5][9] = "Manik";
        first[5][10] = "Tarun";
        first[5][11] = "Veena";
        first[5][12] = "Nalini";
        first[5][13] = "Lekha";
        first[5][14] = "Tanseem";
        first[5][15] = "Keshika";
        first[5][16] = "Kamna";
        first[5][17] = "Jayashri";
        first[5][18] = "Sita";
        first[5][19] = "Shefali";
        first[5][0] = "Gazala";
        first[6][1] = "Amir";
        first[6][2] = "Jope";
        first[6][3] = "Scaulbylausis";
        first[6][4] = "Stanley";
        first[6][5] = "Carrot";
        first[6][6] = "Charles";
        first[6][7] = "Sulu";
        first[6][8] = "Cherry";
        first[6][9] = "Larence";
        first[6][10] = "Talbot";
        first[6][11] = "Amir";
        first[6][12] = "Jope";
        first[6][13] = "Scaulbylausis";
        first[6][14] = "Stanley";
        first[6][15] = "Carrot";
        first[6][16] = "Charles";
        first[6][17] = "Sulu";
        first[6][18] = "Cherry";
        first[6][19] = "Larence";
        first[6][0] = "Talbot";
        
        
        last[0][0] = "Reed";
        last[0][1] = "White";
        last[0][2] = "Smith";
        last[0][3] = "Brown";
        last[0][4] = "Willson";
        last[0][5] = "Young";
        last[0][6] = "Moore";
        last[0][7] = "Miller";
        last[0][8] = "StClaire";
        last[0][9] = "Anderson";
        last[1][0] = "Jones";
        last[1][1] = "Johnson";
        last[1][2] = "Jackson";
        last[1][3] = "Davis";
        last[1][4] = "Harris";
        last[1][5] = "Thomas";
        last[1][6] = "Walker";
        last[1][7] = "King";
        last[1][8] = "Martin";
        last[1][9] = "Lee";
        last[2][0] = "Diaz";
        last[2][1] = "Lopez";
        last[2][2] = "Gomez";
        last[2][3] = "Gonzales";
        last[2][4] = "Gutierrez";
        last[2][5] = "Ortega";
        last[2][6] = "Romera";
        last[2][7] = "Vargas";
        last[2][8] = "Castro";
        last[2][9] = "Cruz";
        last[3][0] = "Nowak";
        last[3][1] = "Smirnov";
        last[3][2] = "Korhonen";
        last[3][3] = "Melnyk";
        last[3][4] = "Popa";
        last[3][5] = "Jovanovic";
        last[3][6] = "Horvath";
        last[3][7] = "Rusu";
        last[3][8] = "Kazlauskas";
        last[3][9] = "Ivanov";
        last[4][0] = "Wang";
        last[4][1] = "Li";
        last[4][2] = "Zhang";
        last[4][3] = "Liu";
        last[4][4] = "Chen";
        last[4][5] = "Yang";
        last[4][6] = "Kim";
        last[4][7] = "Cho";
        last[4][8] = "Park";
        last[4][9] = "Han";
        last[5][0] = "Kumar";
        last[5][1] = "Lal";
        last[5][2] = "Sharma";
        last[5][3] = "Shan";
        last[5][4] = "Jai";
        last[5][5] = "Pal";
        last[5][6] = "Aggarwal";
        last[5][7] = "Raje";
        last[5][8] = "Chande";
        last[5][9] = "Nara";
        last[6][0] = "Blumenfeld";
        last[6][1] = "Jim";
        last[6][2] = "Slat";
        last[6][3] = "Crushtoost";
        last[6][4] = "Candles";
        last[6][5] = "Dude";
        last[6][6] = "Schwartz";
        last[6][7] = "Keeps";
        last[6][8] = "Naipen";
        last[6][9] = "Corbol";
        
        
        death[0] = "gunned down in a back alley";
        death[1] = "slain by horrific clown";
        death[2] = "eaten alive by wolves";
        death[3] = "strangled to death with the murderer's bare hands";
        death[4] = "poisoned and died within the hour";
        death[5] = "burried alive";
        death[6] = "smothered in their sleep";
        death[7] = "struck by a car";
        death[8] = "eaten by a serial killer";
        death[9] = "tied to a rack and torn in half";
        death[10] = "drowned in a toilet bowl";
        death[11] = "drowned in a kitty pool";
        death[12] = "beheaded on live television";
        death[13] = "hit in the face by a wrecking ball";
        death[14] = "shot by Frank's misuse of a bow and arrow";
        death[15] = "sucked into the vaccum of space";
        death[16] = "burned alive by witches";
        death[17] = "turned into a bug and eventually starved";
        death[18] = "devoured by a swarm of bees";
        death[19] = "smote by God himself";
    }
    public void push() {
        status = (firstName() + " " + lastName() + " was " + methodOfDeath() + ". And it's all because YOU pressed the button!");
    }
    public String buttonState(){
        return(status);
    }
    private String firstName() {
        race = rnd.nextInt(7);
        int name = rnd.nextInt(20);
        return(first[race][name]);
    }
    private String lastName() {
        if (race == 0 || race == 1) {
            race = rnd.nextInt(2);
        }
        int name = rnd.nextInt(10);
        return(last[race][name]);
    }
    private String methodOfDeath() {
        int ded = rnd.nextInt(20);
        return(death[ded]);
    }
    
}